trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - task: UseTerraform@0
    inputs:
      terraformVersion: '1.6.0'

  - task: TerraformCLI@0
    inputs:
      command: 'init'

  - task: TerraformCLI@0
    inputs:
      command: 'plan'
      environmentServiceName: '1st-service-connection'  # Replace with your Azure service connection

  - task: TerraformCLI@0
    inputs:
      command: 'apply'
      environmentServiceName: '1st-service-connection'
      args: '-auto-approve'
